modify

diff --git a/caddy b/caddy
--- a/caddy
+++ b/caddy
@@ -3,6 +3,13 @@
 # LCMP Installer for Debian9 x64
 # reference: https://github.com/sayem314/Caddy-Web-Server-Installer
 #
+red=$(tput setaf 1)
+blue=$(tput setaf 2)
+yellow=$(tput setaf 3)
+green=$(tput setaf 4)
+purple=$(tput setaf 5)
+normal=$(tput sgr0)
+
 
 # Do not change any value after installation
 caddypath="/usr/local/bin" # folder where caddyserver will be kept
@@ -42,7 +49,7 @@ about () {
 
 howto () {
 	echo "  Welcome!"
-	echo "  run $(tput setaf 3)$bashname help $(tput sgr0) for help"
+	echo "  run $yellow$bashname help $normal for help"
 	echo ""
 }
 
@@ -69,7 +76,7 @@ isinstalled () {
 	# check if caddy is installed or return error code 1
 	if [[ ! -x $caddypath/caddy ]]; then
 		echo; echo "  Caddy is not installed.";
-		echo "  run $(tput setaf 3)$bashname install$(tput sgr0) to install $caddyname";
+		echo "  run $yellow$bashname install$normal to install $caddyname";
 		echo; return 1
 	fi
 }
@@ -100,7 +107,7 @@ startcaddy () {
 			sudo -H -u $caddyuser $caddypath/caddy -conf="$caddyfile" -quiet=true -pidfile=$caddypid/caddy.pid -agree &
 		fi
 		sleep 1
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
 
 		sleep 1
 		# restart or reload php for smooth environment
@@ -108,7 +115,7 @@ startcaddy () {
 		pids=$(pgrep -nf $caddypath/caddy); caddystatus;
 	else
 		echo ""
-		echo "  $caddyname is already $(tput setaf 2)running$(tput sgr0) on: $pids (PID)"
+		echo "  $caddyname is already $bluerunning$normal on: $pids (PID)"
 		echo ""
 	fi
 
@@ -124,7 +131,7 @@ stopcaddy () {
 	pids=$(pgrep -nf $caddypath/caddy)
 	if [ -z "$pids" ] ; then
 		echo ""
-		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
+		echo "  $caddyname is $redNOT running$normal"
 		echo ""
 	else
 		secs=$(ps -p "$pids" -oetime= | tr '-' ':' | awk -F: '{ total=0; m=1; } { for (i=0; i < NF; i++) {total += $(NF-i)*m; m *= i >= 2 ? 24 : 60 }} {print total}')
@@ -140,7 +147,7 @@ stopcaddy () {
 			kill "$pids"
 		fi
 		sleep 1
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
 	fi
 	systemctl status caddy
 }
@@ -148,8 +155,8 @@ stopcaddy () {
 reloadcaddy () {
 	if [ -z "$pids" ] ; then
 		echo ""
-		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
-		echo "  run $(tput setaf 3)$bashname start$(tput sgr0) to start Caddy"
+		echo "  $caddyname is $redNOT running$normal"
+		echo "  run $yellow$bashname start$normal to start Caddy"
 		echo ""
 	else
 		echo ""
@@ -161,9 +168,9 @@ reloadcaddy () {
 			kill -USR1 "$pids"
 		fi
 		sleep 2
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
 		echo ""
-		echo "  To restart, use $(tput setaf 6)$bashname restart$(tput sgr0)"
+		echo "  To restart, use $(tput setaf 6)$bashname restart$normal"
 		echo "  Refresh your browser at least 3 times to take affect"
 		echo ""
 	fi
@@ -192,7 +199,7 @@ caddystatus () {
 	# Detect Caddy process
 	if [ -z "$pids" ] ; then
 		echo ""
-		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
+		echo "  $caddyname is $redNOT running$normal"
 		echo ""
 	else
 		caddymemusage=$(ps axo rss,comm,pid | grep "$pids" | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' | awk '{print $1}')
@@ -210,7 +217,7 @@ caddystatus () {
 		systemctl status caddy
 
 		echo ""
-		echo "  $caddyname is $(tput setaf 2)running$(tput sgr0)"
+		echo "  $caddyname is $bluerunning$normal"
 		echo "  Caddy (PID: $pids) is using $caddymemusage RAM"
 		echo "  System available RAM $(free -h | grep Mem: | awk '{print $7}')B"
 		echo "  Uptime - $caddyuptime"
@@ -270,7 +277,7 @@ getcaddy () {
 
 	# Star downloading caddy now
 	if ! wget -q $nocert "https://caddyserver.com/download/linux/$cpubits" -O "caddy_linux_custom.tar.gz" --show-progress; then
-		echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		echo "  [$redFAILED$normal]"
 		echo ""
 		echo "  Error: Cannot download Caddy binary!"
 		echo "  https://caddyserver.com/download/linux/$cpubits"
@@ -296,13 +303,13 @@ installcaddy () {
 	# Extract Caddy to appropriate folder
 	echo -n "  Extracting $caddyname to $caddypath..."
 	if ! tar xzf caddy_linux_custom.tar.gz -C $caddypath; then
-		echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		echo "  [$redFAILED$normal]"
 		echo ""
 		echo "  Error: Cannot extract 'caddy_linux_custom.tar.gz'"
 		echo "  Abort."
 		exit 1
 	fi
-	echo " $(tput setaf 2)[DONE]$(tput sgr0)"
+	echo " $blue[DONE]$normal"
 	rm -f caddy_linux_custom.tar.gz # Deleting Caddy archive
 
 	# put the caddy binary in the system wide binary directory and give it appropriate ownership and permissions:
@@ -316,7 +323,7 @@ installcaddy () {
 		echo -n "  Creating user '$caddyuser'..."
 		groupadd $caddyuser
 		useradd -g $caddyuser --home-dir $caddywww --no-create-home --shell /usr/sbin/nologin --system $caddyuser &> /dev/null
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
   fi
 
 	# Creating folders & files
@@ -339,12 +346,12 @@ installcaddy () {
 	# Port setup
 	echo -n "  Binding port using setcap..."
 	if hash setcap 2>/dev/null; then
-		setcap cap_net_bind_service=+ep $caddypath/caddy &>/dev/null && echo "  [$(tput setaf 2)DONE$(tput sgr0)]" || echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		setcap cap_net_bind_service=+ep $caddypath/caddy &>/dev/null && echo "  [$blueDONE$normal]" || echo "  [$redFAILED$normal]"
 	elif hash apt-get 2>/dev/null; then
 		apt-get install libcap2-bin -y &>/dev/null
-		setcap cap_net_bind_service=+ep $caddypath/caddy &>/dev/null && echo "  [$(tput setaf 2)DONE$(tput sgr0)]" || echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		setcap cap_net_bind_service=+ep $caddypath/caddy &>/dev/null && echo "  [$blueDONE$normal]" || echo "  [$redFAILED$normal]"
 	else
-		echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		echo "  [$redFAILED$normal]"
 	fi
 
 	# Show succes message
@@ -386,19 +393,19 @@ updatecaddy () {
 	echo -n "  Removing current $caddyname from $caddypath"
 	sleep 0.2
 	rm -rf "${caddypath:?}/"*
-	echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+	echo "  [$blueDONE$normal]"
 	sleep 0.1
 
 	# Extract Caddy to appropriate folder
 	echo -n "  Extracting $caddyname to $caddypath..."
 	if ! tar xzf caddy_linux_custom.tar.gz -C $caddypath; then
-		echo "  [$(tput setaf 1)FAILED$(tput sgr0)]"
+		echo "  [$redFAILED$normal]"
 		echo ""
 		echo "  Error: Cannot extract 'caddy_linux_custom.tar.gz'"
 		echo "  Abort."
 		exit 1
 	fi
-	echo " $(tput setaf 2)[DONE]$(tput sgr0)"
+	echo " $blue[DONE]$normal"
 
 	# Granting owner access and required permission
 	if id -u $caddyuser >/dev/null 2>&1; then
@@ -422,7 +429,7 @@ installphp () {
 				# Install PHP
 			if hash yum 2>/dev/null; then
 					yum update -y &>/dev/null && yum install sed php-fpm php-cli php-curl curl sudo -y &>/dev/null
-					echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+					echo "  [$blueDONE$normal]"
 					echo "  Installed 'php-fpm php-cli php-curl curl sudo'"
 
 	 		elif hash apt-get 2>/dev/null; then
@@ -438,7 +445,7 @@ installphp () {
 					systemctl enable php7.3-fpm
 					systemctl start php7.3-fpm
 
-					echo " PHP installation was[$(tput setaf 2)DONE$(tput sgr0)]"
+					echo " PHP installation was[$blueDONE$normal]"
      fi
 	 fi
 }
@@ -467,19 +474,20 @@ caddyfile () {
 			echo "  SSL is disabled on non-production server."
 
 			 # if Enabling the DNS Challenge, need cloudflare Email & Global API Key
-		 elif [[ $plugin == "tls.dns.cloudflare" ]]; then
-					echo "  Enter your $(tput setaf 3)Cloudflare Email$(tput sgr0) for enabling the DNS Challenge"
+		 elif [[ "$(echo $plugin | grep "tls.dns.cloudflare")" != "" ]]; then
+					echo "  Enter your $yellowCloudflare Email$normal for enabling the DNS Challenge"
 					read -r -p "  Email: " domainmail
 						until [[ "$domainmail" == *@*.* || "$domainmail" == off ]]; do
 							echo ""
 							echo "  Invalid email"
-							echo "  Type $(tput setaf 3)off$(tput sgr0) if you don't want https"
+							echo "  Type $yellowoff$normal if you don't want https"
 							read -r -p "  Email: " domainmail
 						done
 						echo ""
+ "$(echo $plugin | grep "tls.dns.cloudflare")" != ""
 
 
-						echo "  Enter $(tput setaf 3)Cloudflare Global API Key$(tput sgr0) for enabling the DNS Challenge"
+						echo "  Enter $yellowCloudflare Global API Key$normal for enabling the DNS Challenge"
 						read -r -p "  Global API Key: " domainkey
 					  echo ""
 				else
@@ -488,7 +496,7 @@ caddyfile () {
 						until [[ "$domainmail" == *@*.* || "$domainmail" == off ]]; do
 					echo ""
 					echo "  Invalid email"
-					echo "  Type $(tput setaf 3)off$(tput sgr0) if you don't want https"
+					echo "  Type $yellowoff$normal if you don't want https"
 						read -r -p "  Email: " domainmail
 
 					done
@@ -534,11 +542,10 @@ fi
 	# Check if caddywww exist and setup
 	if [[ ! -e $caddywww ]]; then
 		mkdir -p $caddywww
-
-		# reference official doc: https://github.com/mholt/caddy/issues/2209
-    chown $caddyuser:$caddyuser $caddywww
-    chmod 555 $caddywww
 	fi
+	# reference official doc: https://github.com/mholt/caddy/issues/2209
+	chown $caddyuser:$caddyuser $caddywww
+	chmod 555 $caddywww
 
 	# Generate example html
 	# shellcheck disable=SC1078,SC1079,SC2140
@@ -572,7 +579,7 @@ You should <font color="#D03C3C">replace this file</font>
 
 	echo ""
 	echo "  Done. Caddy has been installed :)"
-	echo "  Run $(tput setaf 3)$bashname start$(tput sgr0) to start $caddyname"
+	echo "  Run $yellow$bashname start$normal to start $caddyname"
 	echo ""
 
 }
@@ -601,7 +608,7 @@ else
 	  fi
 
 		chmod 644 /etc/systemd/system/caddy.service
-		echo "  $(tput setaf 2)DONE$(tput sgr0)"
+		echo "  $blueDONE$normal"
 		echo ""
 	fi
 fi
@@ -679,7 +686,7 @@ removeservice () {
 			systemctl disable caddy &>/dev/null
 			rm -f /etc/systemd/system/caddy.service &>/dev/null
 		fi
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
 	fi
 }
 
@@ -696,7 +703,7 @@ deletecaddydata () {
 		echo -n "  Deleting $caddywww (data)..."
 		sleep 2
 		rm -rf $caddywww # deleting caddy html folder
-		echo "  [$(tput setaf 2)DONE$(tput sgr0)]"
+		echo "  [$blueDONE$normal]"
 		# remove caddy user too if exists
 		if [[ ! $caddyuser == $(whoami) ]]; then
 				userdel $caddyuser # delete caddy user
@@ -704,7 +711,7 @@ deletecaddydata () {
 		fi
 		;;
 	*)
-		echo "  Removing $caddywww (data)... [$(tput setaf 5)Skipped$(tput sgr0)]"
+		echo "  Removing $caddywww (data)... [$purpleSkipped$normal]"
 		;;
 	esac
 }
@@ -760,9 +767,9 @@ checkforupdate () {
 	CADDYV=$(wget -qO- https://api.github.com/repos/mholt/caddy/releases/latest | grep tag_name | sed 's/[^0-9]*//g' | sed 's/^0*//')
 	if [[ $CADDYV -gt $caddyversion ]]; then
 		echo ""
-		echo "  $(tput setaf 1)NOTICE:$(tput sgr0)"
+		echo "  $redNOTICE:$normal"
 		echo "  There is an update available of $caddyname"
-		echo "  run $(tput setaf 3)$bashname update$(tput sgr0) to update"
+		echo "  run $yellow$bashname update$normal to update"
 		echo ""
 	else
 		[[ $CADDYV == "" ]] || echo $(date +%s) > $caddypath/update.check || echo $(date +%s) | sudo tee $caddypath/update.check
@@ -784,7 +791,7 @@ backupcaddy () {
 
 restorecaddy () {
 	if [[ ! -x $caddypath/caddy ]]; then
-		echo "  $(tput setaf 1)WARN:$(tput sgr0)"
+		echo "  $redWARN:$normal"
 		echo "  Caddy is not installed."
 		echo "  It is recommended to install Caddy before restoring."
 		read -r -p "  Press enter to continue anyway!"
